# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

volumes:
  postgres_server_data:
